# Render deployment configuration
# This file automates deployment on Render.com

services:
  # Web Service (combines frontend and backend)
  - type: web
    name: personal-blog
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && NODE_ENV=production node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false  # Set manually in Render dashboard
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false  # Set manually in Render dashboard
      - key: DB_USER
        sync: false  # Set manually in Render dashboard
      - key: DB_PASSWORD
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true  # Render will generate a secure random value
      - key: FRONTEND_URL
        value: https://personal-blog.onrender.com  # Update with your actual URL

  # PostgreSQL Database
  - type: pserv
    name: blog-database
    env: docker
    plan: free
    region: oregon

